### ISSUE TITLE
Plans for handling styles?

### ISSUE THREAD

**Issue by zjr** [cloverfield-tools/universal-react-boilerplate#103]
I'm wondering if there are plans/thoughts/etc. for handling styles in this boilerplate.  I saw in #95 something about _not_ using JS imports.  In #4 sass was floated as a possibility but this wasn't addressed.

I'm a fan of sass, personally, but I know postCSS has had a lot of interest lately.  I believe either could use ExtractTextPlugin and output a css file which could then be referenced in index.html, but not yet sure how well that works with HMR.

**Comment by ericelliott** [comment]
There are lots of options for this, but I don't think any best practices have really emerged. Leave it for now?
