### ISSUE TITLE
Easy the source code access

### ISSUE THREAD

**Issue by romelperez** [cloverfield-tools/universal-react-boilerplate#108]
Wouldn't be a good idea to rename the `source` folder to `src`?

It is related to set the `NODE_PATH` variable to that folder.

Pretty silly suggestion but improves the source code access.

**Comment by ericelliott** [comment]
I don't understand. What is wrong with `source`?

**Comment by romelperez** [comment]
Just to rename it to `src`. Because it is a word heavily used in the whole project. Wouldn't it be better to be shorter?

**Comment by romelperez** [comment]
Never mind. The project is already coupled with the folder name.

**Comment by ericelliott** [comment]
Shorter is not always better.
