### ISSUE TITLE
Implement React Render

### ISSUE THREAD

**Issue by ericelliott** [cloverfield-tools/universal-react-boilerplate#23]
Implement a simple root route and render with [react-engine](https://github.com/paypal/react-engine)

**Comment by SOSANA** [comment]
I will take this on :) 

What about updating package.json file? include it in this task?

**Comment by nkbt** [comment]
@SOSANA I've just updated deps and tested, it is in #26 
It is always better to do such things separately

**Comment by SOSANA** [comment]
@nkbt agreed.

**Comment by ericelliott** [comment]
@SOSANA @nkbt If I don't respond before you get to it, please feel free to merge each other's commits if you're confident about the change.

If anybody proposes tech changes (not just implementing the Roadmap), please wait for others to weigh in.

**Comment by nkbt** [comment]
OK

**Comment by SOSANA** [comment]
I want to do a PR for updated package.json that includes react-engine, reactjs, etc. Should I do this against the Universal branch or master branch?

**Comment by SOSANA** [comment]
@zebulonj let me know if you are going to take this on as per @ericelliott  #13 suggestion

**Comment by ericelliott** [comment]
@SOSANA Master, please. =)

**Comment by ericelliott** [comment]
@SOSANA All yours. Have at it! =)

**Comment by SOSANA** [comment]
@ericelliott right on, I'll open a new issue for views/components that ties in with this PR. For now. Either myself or someone else can take it on.  Excited!

**Comment by zebulonj** [comment]
I'd like to help with this. If someone else is taking lead, I'll contribute where it is needed.

**Comment by ericelliott** [comment]
Great.

@SOSANA Please see the ["hello world" component](https://github.com/stampit-org/react-hello/blob/master/source/hello.js) in [react-hello](https://github.com/stampit-org/react-hello) and make sure to read [Baby's First Reaction](https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd).

I have [a mission for you](https://github.com/stampit-org/react-hello/issues/2), @zebulonj ... You should probably also read [Baby's First Reaction](https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd) if you haven't, yet.

**Comment by ericelliott** [comment]
If you guys want to chat in realtime to touch bases, please use the [JavaScript Questions](https://gitter.im/learn-javascript-courses/javascript-questions) chat.

**Comment by zebulonj** [comment]
@ericelliot I've read it. I'll take a look at the mission you have for me when I'm at my computer.

**Comment by ericelliott** [comment]
:+1:

**Comment by ericelliott** [comment]
Beat you to it. See [this commit](https://github.com/cloverfield-tools/universal-react-boilerplate/commit/3d87ac6aa09b5d206a91c2530b6ef56acef7b379).

Basically scrapped the whole thing and started over. I think best practices have evolved enough since we started this to justify it.
