### ISSUE TITLE
server is in ES5

### ISSUE THREAD

**Issue by vasco3** [cloverfield-tools/universal-react-boilerplate#50]
https://github.com/cloverfield-tools/universal-react-boilerplate/blob/master/app/node_modules/server/index.js contains a bunch of ES5 instead of ES6

**Comment by ericelliott** [comment]
Yeah. Looks like a pretty simple change. PR?

**Comment by vasco3** [comment]
Yep in a bit

**Comment by ericelliott** [comment]
I've scrapped the whole thing and implemented ES6 in [this commit](https://github.com/cloverfield-tools/universal-react-boilerplate/commit/3d87ac6aa09b5d206a91c2530b6ef56acef7b379)

**Comment by vasco3** [comment]
awesome
