### ISSUE TITLE
babel 5 is deprecated :)

### ISSUE THREAD

**Issue by vasco3** [cloverfield-tools/universal-react-boilerplate#57]
`npm WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.`

**Comment by ericelliott** [comment]
Yep. I know. Install and tests failed when I tried to upgrade. One of the problems was due to `eslint-plugin-react` which was caused by an accidental breaking change in ESLint.

I would welcome a PR if you can get everything working. =)

**Comment by nkbt** [comment]
I don't remember exactly all details, but I've recently upgraded everything to babel6 and most recent eslint and eslint-react and it works fine. There was one odd eslint version that broke everything but it was quickly fixed within a day.

**Comment by vasco3** [comment]
haven't upgraded to babel6 yet... taking a break on tools to learn the fundamentals (algorithms, patterns, etc)

**Comment by ericelliott** [comment]
I got this upgrade working in the [React Pure Component Starter](https://github.com/ericelliott/react-pure-component-starter). It should be relatively easy to port.

Who wants to do it?

**Comment by nkbt** [comment]
I'm happy to do that. Going to have a free evening today.

**Comment by ericelliott** [comment]
Nice! =)

**Comment by ericelliott** [comment]
Looking good.
