### ISSUE TITLE
Missing dependencies: transform-es2015-modules-commonjs, transform-object-rest-spread.

### ISSUE THREAD

**Issue by gacosta89** [cloverfield-tools/universal-react-boilerplate#61]
When trying to run the `start` script, I get the following errors:

    ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in <%app.home%>/.babelrc ....
    ReferenceError: Unknown plugin "transform-object-rest-spread" specified in <%app.home%>/.babelrc...

I think someone forgot to include them in package.json.

**Comment by nkbt** [comment]
Will be fixed with #65 (sort of related)
