### ISSUE TITLE
The entry files are missing 'use strict'

### ISSUE THREAD

**Issue by vasco3** [cloverfield-tools/universal-react-boilerplate#64]
Shouldn't the entry files eg. `/source/client/index.js`  have 'use strict' ?

**Comment by nkbt** [comment]
They should.

**Comment by troutowicz** [comment]
I think so. Only ES6 modules use `strict` mode by default.

http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code

**Comment by ericelliott** [comment]
These are ES6  modules. Strict mode is implied.

**Comment by troutowicz** [comment]
But what is considered a module? Doesn't a file need to export something before it can be considered a module?

**Comment by nkbt** [comment]
Actually, source/* are all ES6 modules with implied strict mode.

Though https://github.com/cloverfield-tools/universal-react-boilerplate/blob/master/webpack.config.dev.js and some other scripts are not. We need to add `"use strict"` there.

**Comment by ericelliott** [comment]
:)

**Comment by nkbt** [comment]
Fixed by e35c454

**Comment by ericelliott** [comment]
Thanks!
