### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by nkbt** [cloverfield-tools/universal-react-boilerplate#76]
Simple smoketest to check if everything compiles and renders properly

**Comment by ericelliott** [comment]
:+1: What will you use on the client? I'd like something that can easily do cross browser & cross device testing on Sauce Labs.

**Comment by nkbt** [comment]
I usually run it with selenium (selenium-standalone) in chrome + Nightwatch (to actually write e2e tests in imho a very clean syntax: https://github.com/nkbt/react-component-template/blob/master/test-e2e/Component.js). It's pretty straightforward and works well on both local osx/windows and CI.

I reckon it would be good to make this PR and then we can check for other options if it does not feel good enough.

**Comment by ericelliott** [comment]
> I usually run it with selenium (selenium-standalone) in chrome + Nightwatch (to actually write e2e tests in imho a very clean syntax: https://github.com/nkbt/react-component-template/blob/master/test-e2e/Component.js). It's pretty straightforward and works well on both local osx/windows and CI.

Sounds good to me. I've done similar for many projects. I think it's a good plan for a starting point.
