### ISSUE TITLE
Default pages for error handling

### ISSUE THREAD

**Issue by ericelliott** [cloverfield-tools/universal-react-boilerplate#8]
[express-error-handler](https://github.com/ericelliott/express-error-handler/) allows you to set up some default error routes. We should set up some routes that will return default HTML to browsers and JSON error messages for AJAX and API calls.

**Comment by vasco3** [comment]
I was about to suggest the same thing

**Comment by ericelliott** [comment]
:+1:

**Comment by mahtabhnp** [comment]
Hi,
I’m interested in working on this issue. Could you please assign it to me? This will be my first contribution, and I’m excited to get started. Let me know if there are any specific guidelines or steps I should follow.

Thank you!
@ericelliott

**Comment by ericelliott** [comment]
Hi, this project is long out of date and should no longer be used. It has been supplanted by several better frameworks that handle SSR by default, including Next.JS.

Recently, I have been focused on [SudoLang](https://github.com/paralleldrive/sudolang-llm-support) - specifically, in AI Driven Development workflows, and building UI components that transpile to native Web Components.

See the [Spectrum Web Components](https://developer.adobe.com/photoshop/uxp/2022/uxp-api/reference-spectrum/swc/) for example. My team at Adobe is building sharable components with them.
