### ISSUE TITLE
TypeError: Cannot read property 'visitClass' of undefined

### ISSUE THREAD

**Issue by andresgallego** [cloverfield-tools/universal-react-boilerplate#81]
![screen shot 2016-03-14 at 4 46 05 pm](https://cloud.githubusercontent.com/assets/1014950/13761060/5839fb7e-ea04-11e5-9118-65c5cf4c1ffc.png)

**Comment by ericelliott** [comment]
No worries. Fixing it...

**Comment by ericelliott** [comment]
Should be fixed now. Try again. =)
