### ISSUE TITLE
Changes in react-router-redux  causes syncHistory error.

### ISSUE THREAD

**Issue by satbir121** [cloverfield-tools/universal-react-boilerplate#84]
Steps to reproduce:

```
git clone git@github.com:cloverfield-tools/universal-react-boilerplate.git
npm install
npm run build:dev
npm start
```

Hit `0.0.0.0:3000`

Following error pops up in console:
**_Uncaught TypeError: (0 , _reactRouterRedux.syncHistory) is not a function_**

Caused due to changes in **react-router-redux** pacakage.

**Comment by OneMuppet** [comment]
+1

**Comment by ericelliott** [comment]
Fixed?

**Comment by satbir121** [comment]
Yes.
