### ISSUE TITLE
Blank page when run: __webpack_hmr	GET	(canceled)

### ISSUE THREAD

**Issue by awronski** [cloverfield-tools/universal-react-boilerplate#88]
Hi!

I did `npm install, npm run build:dev, npm start`. And then when I open the browser I get blank page.
In the Developers Tools I see that request to hrm was cancelled:
`__webpack_hmr	GET	(canceled)	eventsource	Other	0 B	67 ms	`

The html source looks ok:
`    <!doctype html>
    <html>
      <head>
        <title>Your Cool React App!</title>
      </head>
      <body>
        <div id='root'><div data-reactid=".el3v6ok6ww" data-react-checksum="-744154979"><h1 data-reactid=".el3v6ok6ww.0"></h1></div></div>
        <script>
          window.BOOTSTRAP_CLIENT_STATE = {"books":{"items":[{"id":1,"text":"Book 1","count":2},{"id":2,"text":"Book 2","count":3},{"id":3,"text":"Book 3","count":4}]}}
        </script>
        <script src="/static/index.js"></script>
      </body>
    </html>`

**Comment by nkbt** [comment]
I reckon that should be fixed by removing HMR https://github.com/cloverfield-tools/universal-react-boilerplate/issues/83

**Comment by nkbt** [comment]
@awronski also check if you run `npm run build:dev` (or `npm run build`) before `npm start`, that might be the case too.

**Comment by awronski** [comment]
I tried both combination (`npm run build:dev` and `npm run build`) but the effect is the same.
There is the state in to source:
` <script>
          window.BOOTSTRAP_CLIENT_STATE = {"books":{"items":[{"id":1,"text":"Book 1","count":2},{"id":2,"text":"Book 2","count":3},{"id":3,"text":"Book 3","count":4}]}}
        </script>`

But the page is blank.

There are no errors at the console.

Here is screenshot with react state:
[screenshot](https://imgur.com/K1JQeUi)

**Comment by nkbt** [comment]
Ah, there is nothing on `/` route. It is actually blank. The route with books and buttons is `/test-data`

**Comment by ericelliott** [comment]
I know. I was lazy. Super confusing! We need a pull request to put something on the `/` route. I'm definitely open to something. Just keep it simple. =)

**Comment by ericelliott** [comment]
An explainer page with some simple docs about what this project is and a link to other routes to test would probably be a good idea.

**Comment by awronski** [comment]
With `http://127.0.0.1:3000/test-data` it works ok :+1: 
Thanks!

**Comment by ericelliott** [comment]
Great! =)
